title: "Programación Estructurada en C"
description: "Repositorio de actividades y evidencias - Lenguaje C"
author: "Mateo Loyo Martinez"
theme: minima

exclude:
  - README.md

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag