# Configuracion Jekyll para GitHub Pages
title: "Programacion Estructurada"
description: "Repositorio de actividades y evidencias - Lenguaje C"
author: "Mateo Loyo Martinez"
theme: minima

minima:
  skin: classic

header_pages:
  - README.md

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
