# Configuracion Jekyll para GitHub Pages
# Dejar title vacio para que no aparezca en el header
title: ""
description: "Repositorio de actividades y evidencias - Lenguaje C"
author: "Mateo Loyo Martinez"
theme: minima

minima:
  skin: classic

header_pages:
  - README.md

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
